require:
  - rubocop
  - rubocop-minitest

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false